name: Dependency Management and Vulnerability Scanning and secret scanning
on:
  # Trigger workflow met pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  

  - name: test-workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - run: python echo(1)
    - run: python exit(0)

schedule:
    - cron: "0 0 2 * * Mon"  # maandag om 2 uur
