name: workflow_secure_pipeline_AL

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 2 * * Mon'  # Maandag om 2 uur

jobs:
  code-scannen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - run: |
          pip install --upgrade pip
          pip install bandit 
      - name: Gebruik Bandit
        uses: mdegis/bandit-action@v1.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          level: "LOW"
          confidence: "HIGH"
          exit_zero: false
      - name: Bandit Check
        run: bandit -r -lll -ii .

  dependancies-nakijken:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  
      - name: Set up Python 3.13
        uses: actions/setup-python@v3
        with:
          python-version: '3.13'
      - run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Controleer dependancies op kwetsbaarheden
        run: |
          pip install safety
          safety check
