name: workflow_secure_pipeline_AL
on:
  # Trigger workflow met pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '0 2 * * Mon'  # maandag om 2 uur

  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - run: echo("1")
    - run: exit(0)