name: workflow_secure_pipeline_AL
on:
  # Trigger workflow met pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '0 2 * * Mon'  # maandag om 2 uur

  
jobs:
  code-scannen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - run: pip install bandit
    - name: gebruik bandit
      uses: mdegis/bandit-action@v1.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        path: "."
        level: UNDEFINED
        confidence: UNDEFINED
        exit_zero: true
    
  dependancies-nakijken:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.13'
    - run: echo 1